"""Write the LangGraph topology as Mermaid to docs/graph.md.

Usage:
    python scripts/draw_graph.py

Drawing needs no data: nodes are never executed, so placeholder components are used.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src.graph import Components, Settings, build_graph  # noqa: E402


def mermaid() -> str:
    placeholders = Components(None, None, None, None, None, llm_available=False)
    return build_graph(Settings(data_dir=ROOT / "data"), placeholders).get_graph().draw_mermaid().strip()


def main():
    doc = f"""# PharmGuard graph

A LangGraph state machine with deterministic planning and bounded LLM retry
(`src/graph/builder.py`). Generated by `python scripts/draw_graph.py`; a test
fails if this file is stale. Dotted arrows are conditional edges:

- **plan**: fewer than 2 unique resolved drugs → `template`; otherwise `retrieve`.
- **retrieve**: FAERS enabled → `faers`; deterministic mode or no LLM configured → `template`; otherwise `generate_llm`.
- **generate_llm**: success → `validate`; LLM error with attempts left → `generate_llm`; none left → `template`.
- **validate**: pass → `finalize`; fail with attempts left → `generate_llm` (findings + rejected draft as feedback); none left → `template`.
- **finalize**: appends the disclaimer and provenance line, validates the final report, and records `report_source`.

```mermaid
{mermaid()}
```
"""
    out = ROOT / "docs" / "graph.md"
    out.write_text(doc)
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
